// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef TIMESTAMP_LOG_ODB_HXX
#define TIMESTAMP_LOG_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "../entities/timestamp_log.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // timestamp_log
  //
  template <>
  struct class_traits< ::timestamp_log >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::timestamp_log >
  {
    public:
    typedef ::timestamp_log object_type;
    typedef ::timestamp_log* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // timestamp_log
  //
  template <typename A>
  struct query_columns< ::timestamp_log, id_mysql, A >
  {
    // id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    id_type_;

    static const id_type_ id;

    // ts_issue
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ts_issue_type_;

    static const ts_issue_type_ ts_issue;

    // ts_certificate
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ts_certificate_type_;

    static const ts_certificate_type_ ts_certificate;

    // ts_time
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ts_time_type_;

    static const ts_time_type_ ts_time;

    // user_ip
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    user_ip_type_;

    static const user_ip_type_ user_ip;

    // ts_status
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ts_status_type_;

    static const ts_status_type_ ts_status;

    // ts_info
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    ts_info_type_;

    static const ts_info_type_ ts_info;
  };

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::id_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  id (A::table_name, "`id`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::ts_issue_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  ts_issue (A::table_name, "`ts_issue`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::ts_certificate_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  ts_certificate (A::table_name, "`ts_certificate`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::ts_time_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  ts_time (A::table_name, "`ts_time`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::user_ip_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  user_ip (A::table_name, "`user_ip`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::ts_status_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  ts_status (A::table_name, "`ts_status`", 0);

  template <typename A>
  const typename query_columns< ::timestamp_log, id_mysql, A >::ts_info_type_
  query_columns< ::timestamp_log, id_mysql, A >::
  ts_info (A::table_name, "`ts_info`", 0);

  template <typename A>
  struct pointer_query_columns< ::timestamp_log, id_mysql, A >:
    query_columns< ::timestamp_log, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::timestamp_log, id_mysql >:
    public access::object_traits< ::timestamp_log >
  {
    public:
    struct id_image_type
    {
      int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      int id_value;
      my_bool id_null;

      // ts_issue_
      //
      details::buffer ts_issue_value;
      unsigned long ts_issue_size;
      my_bool ts_issue_null;

      // ts_certificate_
      //
      details::buffer ts_certificate_value;
      unsigned long ts_certificate_size;
      my_bool ts_certificate_null;

      // ts_time_
      //
      details::buffer ts_time_value;
      unsigned long ts_time_size;
      my_bool ts_time_null;

      // user_ip_
      //
      details::buffer user_ip_value;
      unsigned long user_ip_size;
      my_bool user_ip_null;

      // ts_status_
      //
      details::buffer ts_status_value;
      unsigned long ts_status_size;
      my_bool ts_status_null;

      // ts_info_
      //
      details::buffer ts_info_value;
      unsigned long ts_info_size;
      my_bool ts_info_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::timestamp_log, id_common >:
    public access::object_traits_impl< ::timestamp_log, id_mysql >
  {
  };

  // timestamp_log
  //
}

#include "timestamp_log-odb.ixx"

#include <odb/post.hxx>

#endif // TIMESTAMP_LOG_ODB_HXX
