// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef SM2_KEY_INFO_ODB_HXX
#define SM2_KEY_INFO_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "../entities/sm2_key_info.h"

#include <memory>
#include <cstddef>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // sm2_key_info
  //
  template <>
  struct class_traits< ::sm2_key_info >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::sm2_key_info >
  {
    public:
    typedef ::sm2_key_info object_type;
    typedef ::sm2_key_info* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef int id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/mysql/version.hxx>
#include <odb/mysql/forward.hxx>
#include <odb/mysql/binding.hxx>
#include <odb/mysql/mysql-types.hxx>
#include <odb/mysql/query.hxx>

namespace odb
{
  // sm2_key_info
  //
  template <typename A>
  struct query_columns< ::sm2_key_info, id_mysql, A >
  {
    // key_id
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    key_id_type_;

    static const key_id_type_ key_id;

    // key_purpose
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    key_purpose_type_;

    static const key_purpose_type_ key_purpose;

    // key_mod
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        int,
        mysql::id_long >::query_type,
      mysql::id_long >
    key_mod_type_;

    static const key_mod_type_ key_mod;

    // pri_D
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    pri_D_type_;

    static const pri_D_type_ pri_D;

    // pub_X
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    pub_X_type_;

    static const pub_X_type_ pub_X;

    // pub_Y
    //
    typedef
    mysql::query_column<
      mysql::value_traits<
        ::std::string,
        mysql::id_string >::query_type,
      mysql::id_string >
    pub_Y_type_;

    static const pub_Y_type_ pub_Y;
  };

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::key_id_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  key_id (A::table_name, "`key_id`", 0);

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::key_purpose_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  key_purpose (A::table_name, "`key_purpose`", 0);

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::key_mod_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  key_mod (A::table_name, "`key_mod`", 0);

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::pri_D_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  pri_D (A::table_name, "`pri_D`", 0);

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::pub_X_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  pub_X (A::table_name, "`pub_X`", 0);

  template <typename A>
  const typename query_columns< ::sm2_key_info, id_mysql, A >::pub_Y_type_
  query_columns< ::sm2_key_info, id_mysql, A >::
  pub_Y (A::table_name, "`pub_Y`", 0);

  template <typename A>
  struct pointer_query_columns< ::sm2_key_info, id_mysql, A >:
    query_columns< ::sm2_key_info, id_mysql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::sm2_key_info, id_mysql >:
    public access::object_traits< ::sm2_key_info >
  {
    public:
    struct id_image_type
    {
      int id_value;
      my_bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // key_id_
      //
      int key_id_value;
      my_bool key_id_null;

      // key_purpose_
      //
      int key_purpose_value;
      my_bool key_purpose_null;

      // key_mod_
      //
      int key_mod_value;
      my_bool key_mod_null;

      // pri_D_
      //
      details::buffer pri_D_value;
      unsigned long pri_D_size;
      my_bool pri_D_null;

      // pub_X_
      //
      details::buffer pub_X_value;
      unsigned long pub_X_size;
      my_bool pub_X_null;

      // pub_Y_
      //
      details::buffer pub_Y_value;
      unsigned long pub_Y_size;
      my_bool pub_Y_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          my_bool*);

    static void
    bind (MYSQL_BIND*,
          image_type&,
          mysql::statement_kind);

    static void
    bind (MYSQL_BIND*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          mysql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef mysql::object_statements<object_type> statements_type;

    typedef mysql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::sm2_key_info, id_common >:
    public access::object_traits_impl< ::sm2_key_info, id_mysql >
  {
  };

  // sm2_key_info
  //
}

#include "sm2_key_info-odb.ixx"

#include <odb/post.hxx>

#endif // SM2_KEY_INFO_ODB_HXX
